name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Haskell
      uses: haskell-actions/setup@v2.7.9
      with: 
        ghc-version: 9.6.6
        cabal-version: 3.12
        enable-stack: true
        stack-version: 3.3.1
        stack-setup-ghc: true

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        stack update
        stack build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: stack build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: stack test all
